### ISSUE TITLE
Research secondary API to compliment amiibo API

### ISSUE THREAD

**Issue by LSabin23** [Alex-Soucy/its-amiibo-mario#10]
This issue represents the work done to research the secondary API to compliment the amiibo API and discusses the issues that came up during this research. This is being logged to illustrate non-commit related efforts.

An incredibly collaborative and supportive research effort was undertaken by all project members to locate the second API and each of us met our own frustrations and roadblocks during our discoveries.

## eBay Finding API:
- eBay's Finding API is meant to be used to locate listings on ebay by keywords which we intended to use to display these listings based on the amiibo character a user searches
- eBay's developer program requires one business day to review credentials of applicants which delayed project progress because many of their documents around their APIs are locked behind a developer program login (requires approval)
- There is a lack of clear documentation around CORS support for eBay API's and we did not discover that the eBay Finding API was not supported until after attempting to make a call
- The eBay Finding API does not utilize the Fetch methods which were practiced during coursework so it took additional research and testing to work through the scant tutorial documentation and understand how to attempt to utilize the API

## eBay Buying API and eBay Shopping APIs:
- These APIs had similar issues as the aforementioned API, but were also met with the necessity to implement user authentication to allow users to see and purchase eBay products with their eBay accounts

## Rapid API:
- This is a search engine API that would've provided search results based on the amiibo character name the user entered and was saved as a fallback if needed.

## Amazon API:
- This API was locked behind a subscriber service

## Nintendo eShop API:
- This API was almost what we were looking for, but would only have been able to show users the games their amiibo character came from and not the cards or figurines as Nintendo's eShop is only for digital games and not physical goods. Additionally, this API does not provide responses in JSON format.

## Giant Bomb API:
- This API would have given us reviews for games rather than the game or amiibo card/figure itself which could help a user decide if they were interested in the game the amiibo came from. This API also lacked significant documentation around how to utilize it.

## CheapShark API:
- This API would have given us deals on games associated with the amiibo character searched, but many games are only available on Nintendo consoles and CheapShark mostly focuses on PC games.

## SerpAPI:
- This API works with Google search results however, it is not CORS supported and we were directed to avoid non-CORS supported APIs for this project.

## IGDB API:
- This API required filling out an application and obtaining approval as well as a Twitch account to utilize and was abandoned due to time constraints.

## Walmart API:
- This API needed authorization.

## Best Buy API:
- This API needed authorization.

**Comment by mkanczuzewski** [comment]
### NewEgg 

- Requires a professional account to use and cannot be done for educational purposes.

### STEAM WEB API

- Interesting possibility but only allows for the game team Fortress 2

### RAWG 

- This is a game database at https://rawg.io/apidocs may be an option. Need Alex to git us a site URL on github for our solution to sign up.
- After further research on https://rawgthedocs.orels.sh/api/#basics  RAWG.io relies on a token header for authentication. To acquire a token - use the /auth/login route. The returned key can then be used to authenticate all of the requests to the service. Login authentication is beyond the scope of this project so this cannot be used. 

### Pinterest

- Requires a Business account to set it up and does not allow for educational purposes.  https://developers.pinterest.com/docs/api/v5/

### Meijer, Target, Kroger

- Have internal API that cannot be accessed externally.

### Walmart and Gamestop

- Requires a company name to register for a key

**Comment by mkanczuzewski** [comment]
### Giant Bomb
I reviewed this further over the course of several hours and was able to put together a request as listed below. The data coming back has some things we could use if we change the user story. HOWEVER the individual listings are all over the place because they include things about any character with that name from any game (Mario Lemieux for hockey returns as well as Mario for nintendo) .  This is the request:
https://www.giantbomb.com/api/character/3005-177/?api_key=730e075ef96a4d9d672f4a252c98ed7ef9e21d16&format=json
