### ISSUE TITLE
Search logic to JavaScript

### ISSUE THREAD

**Issue by Obiwan-Jabronii** [Alex-Soucy/its-amiibo-mario#3]
- [x] Add search logic (user input via form; user searches for amiibo by character name?)
- [x] Define user Input to define query link
- [x] Function to fetch data from aiimbo API
- [x] Function Display results via initial Fetch from aiimbo by Nintendo API
- [x] Define searchterm for secondary API
- [x] #4

**Comment by erin-michon** [comment]
**Search Engine Result Page API Resource Identified:**

I subscribed (freemium) to a search API and confirmed that I was able to fetch JSON using a hard coded query of "Mario Amiibo".  Posting screenshots for reference/discussion

![image](https://user-images.githubusercontent.com/89706633/141323092-94cf3740-7f86-4a95-a34e-17eba119dd0b.png)

![image](https://user-images.githubusercontent.com/89706633/141323151-2185ccff-ef82-4cf7-825e-77ca9b6113de.png)
