### ISSUE TITLE
Add ability to shop through 3rd party API

### ISSUE THREAD

**Issue by Obiwan-Jabronii** [Alex-Soucy/its-amiibo-mario#4]
- [x] provide a link to the user through a 3rd party API to a page where the user can browse games and/or amiibo figures/cards related to their searched amiibo for purchase

**Comment by erin-michon** [comment]
Optional/Possible Search Engine Result Page API Resource Identified:

I subscribed (freemium) to a search API and confirmed that I was able to fetch JSON using a hard coded query of "Mario Amiibo". Posting for discussion later/if needed

https://rapidapi.com/contextualwebsearch/api/web-search/


NOTE:  I am going to keep looking for a product specific API

**Comment by LSabin23** [comment]
Created finding-listings-logic branch from java-fetch-logic branch to work on this using the ebay Finding API.
